CREATE TABLE `skills` (
  `playerName` varchar(15) NOT NULL default '',
  `Attacklvl` double default NULL,
  `Attackxp` double default NULL,
  `Defencelvl` double default NULL,
  `Defencexp` double default NULL,
  `Strengthlvl` double default NULL,
  `Strengthxp` double default NULL,
  `Hitpointslvl` double default NULL,
  `Hitpointsxp` double default NULL,
  `Rangelvl` double default NULL,
  `Rangexp` double default NULL,
  `Prayerlvl` double default NULL,
  `Prayerxp` double default NULL,
  `Magiclvl` double default NULL,
  `Magicxp` double default NULL,
  `Cookinglvl` double default NULL,
  `Cookingxp` double default NULL,
  `Woodcuttinglvl` double default NULL,
  `Woodcuttingxp` double default NULL,
  `Fletchinglvl` double default NULL,
  `Fletchingxp` double default NULL,
  `Fishinglvl` double default NULL,
  `Fishingxp` double default NULL,
  `Firemakinglvl` double default NULL,
  `Firemakingxp` double default NULL,
  `Craftinglvl` double default NULL,
  `Craftingxp` double default NULL,
  `Smithinglvl` double default NULL,
  `Smithingxp` double default NULL,
  `Mininglvl` double default NULL,
  `Miningxp` double default NULL,
  `Herblorelvl` double default NULL,
  `Herblorexp` double default NULL,
  `Agilitylvl` double default NULL,
  `Agilityxp` double default NULL,
  `Thievinglvl` double default NULL,
  `Thievingxp` double default NULL,
  `Slayerlvl` double default NULL,
  `Slayerxp` double default NULL,
  `Farminglvl` double default NULL,
  `Farmingxp` double default NULL,
  `Runecraftlvl` double default NULL,
  `Runecraftxp` double default NULL,
  `Hunterlvl` double default NULL,
  `Hunterxp` double default NULL,
  `Constructionlvl` double default NULL,
  `Constructionxp` double default NULL,
  `Summoninglvl` double default NULL,
  `Summoningxp` double default NULL,
  PRIMARY KEY  (`playerName`)
) ENGINE=MyISAM;

CREATE TABLE `skillsoverall` (
  `playerName` varchar(15) NOT NULL default '',
  `lvl` int(11) default NULL,
  `xp` int(11) default NULL,
  PRIMARY KEY  (`playerName`)
) ENGINE=MyISAM;